Mine/urls.py
from django.conf.urls import url

from Mine import views

urlpatterns = [
    url(r'^mine/', views.mine, name='mine')
]

User/urls.py
from django.conf.urls import url

from User import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^checkName/', views.checkName, name='checkName'),
    url(r'^send_mail/', views.send_email, name='send_email'),
    url(r'^account/', views.account, name='account'),
    url(r'^get_code/', views.get_code, name='get_code'),
    url(r'^loggout/', views.logout, name='logout')

]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/', include('Home.urls', namespace='axfhome')),
    url(r'^axfcart/', include('Cart.urls', namespace='axfcart')),
    url(r'^axfmine/', include('Mine.urls', namespace='axfmine')),
    url(r'^axfmarket/', include('Market.urls', namespace='axfmarket')),
    url(r'^axfuser/', include('User.urls', namespace='axfuser')),
    url(r'^axforder/', include('Order.urls', namespace='axforder'))
]

Mine/models.py
from django.db import models

# Create your models here.

Mine/views.py
from django.shortcuts import render

# Create your views here.
from User.models import AxfUser


def mine(request):
    user_id = request.user_id
    if user_id:
        user = AxfUser.objects.get(pk=user_id)
        context = {
            'user': user
        }
        return render(request, 'axf/main/mine/mine.html', context=context)
    else:
        return render(request, 'axf/main/mine/mine.html')

templates/axf/main/mine/mine.html
{% extends 'base_main.html' %}

{% load static %}

{% block title %}
    {{ block.super }}
    我的
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/mine/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/user.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div id="mine">
        <div class="fixed">

            {% if user.id %}
                <span>
               <img src='/static/upload/{{ user.icon }}'>
            </span>
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            {% if user.id %}
                <p>{{ user.name }}</p>
                {% else %}
                <p id="login">
                    未登录
                </p>
             {% endif %}
            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>
            <p>
                <span class="glyphicon glyphicon-heart"></span>商品收藏
            </p>
        </div>

        <div id="regis">注册</div>
        <div class="mine">
            <p>
                <a>全部订单></a>
            </p>
            <p>
                全部订单
            </p>


            <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            <dd>待付款</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            <dd>待收货</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            <dd>待评价</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            <dd>取款/售后</dd>
                            </dt>
                        </dl>
                    </li>
                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            <dd>积分商城</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            <dd>优惠券</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            <dd>收货地址</dd>
                            </dt>
                        </dl>
                    </li>

                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            <dd>客服反馈</dd>
                            </dt>
                        </dl>
                    </li>

                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-certificate"></span>
                            <dd>关于我们</dd>
                            </dt>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if user.id %}
                 <p>
                <a href="{% url 'axfuser:logout' %}">退出</a>

            {% endif %}
        </div>

    </div>
{% endblock %}