Cart/urls.py
from django.conf.urls import url

from Cart import views

urlpatterns = [
    url(r'^cart/', views.cart, name='cart'),
    url(r'^addToCart/', views.addToCart),
    url(r'^subToCart/', views.subToCart),
    url(r'^changeStatus/', views.changestatus),
    url(r'^allselect/', views.allselect)
]

Home/urls.py
from django.conf.urls import url

from Home import views

urlpatterns = [
    url(r'^home/', views.home, name='home')
]

Market/urls.py
from django.conf.urls import url

from Market import views

urlpatterns = [
    url(r'^market/', views.market, name='market')
]

Mine/urls.py
from django.conf.urls import url

from Mine import views

urlpatterns = [
    url(r'^mine/', views.mine, name='mine')
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/', include('Home.urls', namespace='axfhome')),
    url(r'^axfcart/', include('Cart.urls', namespace='axfcart')),
    url(r'^axfmine/', include('Mine.urls', namespace='axfmine')),
    url(r'^axfmarket/', include('Market.urls', namespace='axfmarket')),
    url(r'^axfuser/', include('User.urls', namespace='axfuser')),
    url(r'^axforder/', include('Order.urls', namespace='axforder'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>

    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    {% block ext_css %}

    {% endblock %}
</head>
<body>

    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    {% block ext_js %}

    {% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% load static %}


{% block ext_css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}



{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}



{% block footer %}
    {{ block.super }}

    <footer>
        <a href="{% url 'axfhome:home' %}">
            <dl class="home">
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axfmarket:market' %}">
                <dl class="market">
                    <dt>
                        <span></span>
                    </dt>
                    <dd>闪购</dd>
                </dl>
            </a>
        <a href="{% url 'axfcart:cart' %}">
                <dl class="cart">
                    <dt>
                        <span></span>
                    </dt>
                    <dd>购物车</dd>
                </dl>
            </a>
        <a href="{% url 'axfmine:mine' %}">
                <dl class="mine">
                    <dt>
                        <span></span>
                    </dt>
                    <dd>我的</dd>
                </dl>
        </a>

    </footer>


{% endblock %}

templates/base_order.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/order.css' %}">
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}