Order/urls.py
from django.conf.urls import url

from Order import views

urlpatterns = [
    url(r'^makeOrder/', views.makeOrder),
    url(r'^orderDetail/', views.orderDetail),
    url(r'^testPay/', views.testPay)
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/', include('Home.urls', namespace='axfhome')),
    url(r'^axfcart/', include('Cart.urls', namespace='axfcart')),
    url(r'^axfmine/', include('Mine.urls', namespace='axfmine')),
    url(r'^axfmarket/', include('Market.urls', namespace='axfmarket')),
    url(r'^axfuser/', include('User.urls', namespace='axfuser')),
    url(r'^axforder/', include('Order.urls', namespace='axforder'))
]

Order/models.py
from django.db import models

# Create your models here.
from Market.models import AxfGoods
from User.models import AxfUser


class AxfOrder(models.Model):
    o_user = models.ForeignKey(AxfUser)
    o_price = models.FloatField()

    class Meta:
        db_table = 'axf_order'


class AxfOrderGoods(models.Model):
    og_order = models.ForeignKey(AxfOrder)
    og_goods = models.ForeignKey(AxfGoods)

    og_num = models.IntegerField()

    class Meta:
        db_table = 'axf_ordergoods'

Order/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from Cart.models import AxfCart
 
  
  
from Cart.view_containt import get_total_price
from Order.models import AxfOrder, AxfOrderGoods
from axf.settings import PRIVATE_KEY, PUBLIC_KEY


@csrf_exempt
def makeOrder(request):
    # 在订单的页面 应该展示的是ordergoods的数据
    # ordergoods依赖于order
    # order依赖于user

    user_id = request.session.get('user_id')

    order = AxfOrder()
    order.o_user_id = user_id
    order.o_price = get_total_price(user_id)
    order.save()

    carts = AxfCart.objects.filter(c_user_id=user_id).filter(c_is_select=True)

    for cart in carts:
        ordergoods = AxfOrderGoods()
        ordergoods.og_order = order
        ordergoods.og_goods = cart.c_goods
        ordergoods.og_num = cart.c_goods_num

        ordergoods.save()
        cart.delete()

    data = {
        'msg': 'ok',
        'status': 200,
        'order_id': order.id
    }

    return JsonResponse(data=data)


def orderDetail(request):
    order_id = request.GET.get('order_id')

    order = AxfOrder.objects.get(pk=order_id)
    # print('--------------------')
    # print(order.id)

    context = {
        'order': order
    }
    return render(request, 'axf/order/orderdetail.html', context=context)


def testPay(request):
    alipay = AliPay(
        appid="2016102200741149",
        app_notify_url=None,  # 默认回调url
        app_private_key_string=PRIVATE_KEY,
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        alipay_public_key_string=PUBLIC_KEY,
        sign_type="RSA2",  # RSA 或者 RSA2
        debug=False  # 默认False
    )
    # 如果你是Python 2用户（考虑考虑升级到Python 3吧），请确保非ascii的字符串为utf8编码：
    # subject = u"测试订单".encode("utf8")
    # 如果你是 Python 3的用户，使用默认的字符串即可
    subject = "口罩"

    # 电脑网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
    order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no="20200512",
        total_amount=99,
        subject=subject,
        return_url="https://example.com",
        notify_url="https://example.com/notify"  # 可选, 不填则使用默认notify url
    )
    return redirect('https://openapi.alipay.com/gateway.do? + order_string')

templates/axf/order/orderdetail.html
{% extends 'base_order.html' %}

{% load static %}

{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/orderdetail.css' %}">
{% endblock %}

{% block title %}
    {{ block.super }}
    订单详情
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="container">

        <h3>订单编号：{{ order.id }}</h3>

        {% for ordergoods in order.axfordergoods_set.all %}
            <div class="menuList">
                <a href="">
                    <img src="/static{{ ordergoods.og_goods.productimg }}">
                    <p>{{ ordergoods.og_goods.productlongname }}</p>
                    <p class="presentPrice">{{ ordergoods.og_goods.price }}</p>
                </a>
                <section>
                    <span>{{ ordergoods.og_num }}</span>
                </section>

            </div>
        {% endfor %}

        <div class="total_price">总计:
            <span id="total_price">{{ order.o_price }}</span>
        </div>
    </div>

{% endblock %}