User/urls.py
from django.conf.urls import url

from User import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^checkName/', views.checkName, name='checkName'),
    url(r'^send_mail/', views.send_email, name='send_email'),
    url(r'^account/', views.account, name='account'),
    url(r'^get_code/', views.get_code, name='get_code'),
    url(r'^loggout/', views.logout, name='logout')

]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/', include('Home.urls', namespace='axfhome')),
    url(r'^axfcart/', include('Cart.urls', namespace='axfcart')),
    url(r'^axfmine/', include('Mine.urls', namespace='axfmine')),
    url(r'^axfmarket/', include('Market.urls', namespace='axfmarket')),
    url(r'^axfuser/', include('User.urls', namespace='axfuser')),
    url(r'^axforder/', include('Order.urls', namespace='axforder'))
]

User/models.py
from django.db import models


# Create your models here.

class AxfUser(models.Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=256)
    email = models.EmailField()
    icon = models.ImageField(upload_to='icons')
    active = models.BooleanField(default=False)
    token = models.CharField(max_length=256)

    class Meta:
        db_table = 'axf_user'

User/views.py
import uuid
from io import BytesIO

from PIL import Image
from PIL.ImageDraw import ImageDraw
from PIL import ImageFont
from django.contrib.auth.hashers import make_password, check_password
from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from User.models import AxfUser
from User.view_constaint import send_email
from axf import settings


def login(request):
    if request.method == 'GET':
        return render(request, 'axf/user/login.html')
    else:
        # 先判断验证码是否正确
        # 然后判断用户名和密码(减少数据库的读取操作)
        imgcode = request.POST.get('imgcode')
        imgcode1 = request.session.get('verify_code')

        if imgcode.lower() == imgcode1.lower():
            name = request.POST.get('name')
            users = AxfUser.objects.filter(name=name)

            if users.exists():
                user = users.first()
                password = request.POST.get('password')

                result = check_password(password, user.password)
                if result:
                    if user.active == 1:
                        request.session['user_id'] = user.id
                        return redirect(reverse('axfmine:mine'))
                    else:
                        context = {
                            'msg': '账号未激活'
                        }
                        return render(request, 'axf/user/login.html', context=context)
                else:
                    context = {
                        'msg': '密码输入错误'
                    }
                    return render(request, 'axf/user/login.html', context=context)
            else:
                context = {
                    'msg': '用户名输入错误'
                }
                return render(request, 'axf/user/login.html', context=context)
        else:
            context = {
                'msg': '验证码输入错误'
            }
            return render(request, 'axf/user/login.html', context=context)


def register(request):
    if request.method == 'GET':
        return render(request, 'axf/user/register.html')
    else:
        name = request.POST.get('name')
        password = request.POST.get('password')
        email = request.POST.get('email')
        icon = request.FILES.get('icon')

        new_password = make_password(password)

        user = AxfUser()

        user.name = name
        user.password = new_password
        user.email = email
        user.icon = icon

        token = uuid.uuid4()
        user.token = token
        user.save()

        cache.set(token, user.id, timeout=60)

        send_email(name, token, email)
        return redirect(reverse('axfuser:login'))


def checkName(request):
    # 注册时检查用户名是否可以使用
    name = request.GET.get('name')
    users = AxfUser.objects.filter(name=name)

    data = {
        'msg': '用户名可以使用',
        'status': 200
    }
    if users.count() > 0:
        data['msg'] = '用户名已存在'
        data['status'] = 201
        return JsonResponse(data=data)
    else:
        return JsonResponse(data=data)


def account(request):
    token = request.GET.get('token')
    user_id = cache.get(token)
    name = request.GET.get('name')
    print(name)

    if user_id:
        user = AxfUser.objects.filter(token=token)[0]

        user.active = True
        user.save()
        # 将缓存中的token删除，以免多次激活
        cache.delete(token)

        return HttpResponse('激活成功')

    # elif request.GET.get('')

    else:
        return HttpResponse('邮件已过期，请重新发送！！！')


def get_code(request):
    # 登入时，第一步检查验证码
    # 初始化画布，初始化画笔

    mode = "RGB"

    size = (250, 50)

    red = get_color()

    green = get_color()

    blue = get_color()

    color_bg = (red, green, blue)

    image = Image.new(mode=mode, size=size, color=color_bg)

    imagedraw = ImageDraw(image, mode=mode)

    imagefont = ImageFont.truetype(settings.FONT_PATH, 50)

    verify_code = generate_code()

    request.session['verify_code'] = verify_code

    for i in range(4):
        fill = (get_color(), get_color(), get_color())
        imagedraw.text(xy=(40 * i, 0), text=verify_code[i], font=imagefont, fill=fill)

    for i in range(1000):
        fill = (get_color(), get_color(), get_color())
        xy = (random.randrange(201), random.randrange(100))
        imagedraw.point(xy=xy, fill=fill)

    fp = BytesIO()

    image.save(fp, "png")

    return HttpResponse(fp.getvalue(), content_type="image/png")


import random


def get_color():
    return random.randrange(256)


def generate_code():
    source = "qwertyuiopasdfghjklzxcvbnm1234567890QWERTYUIOPASDFGHJKLZXCVBNM"

    code = ""

    for i in range(4):
        code += random.choice(source)

    return code


def logout(request):
    request.session.flush()
    return redirect(reverse('axfuser:login'))

templates/axf/user/active.html
尊敬的vip{{ name }}您好：<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎注册爱鲜峰App，点击下方链接
<a href="{{ url }}">{{ url }}</a>激活账户<br>
如果点击后未生效，请求一下链接{{ url }}到浏览器地址栏访问

templates/axf/user/login.html
{% extends 'base_user.html' %}

{% load static %}

{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}

{% block title %}
    {{ block.super }}
    登入
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/login.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/user/js/md5.js' %}"></script>

{% endblock %}

{% block content %}
    {{ block.super }}

    <form action="{% url 'axfuser:login' %}" method="post">
        <span style="color: red">{{ msg }}</span>
        {% csrf_token %}
        <div class="container">
            <div class="form-group">
                <label for="exampleInputName">用户名：</label>
                <input type="text" class="form-control" id="name" name='name' placeholder="请输入用户名">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword">密码：</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码">
            </div>

            <div class="form-group">
                <label for="img1">验证码：</label>
                <input type="text" class="form-control" id="img1" name="imgcode" placeholder='请输入验证码'>
            </div>
            <img src="/axfuser/get_code/" alt="" id="changeimg">

            <div>
                <button type="submit" class="btn btn-success btn-block">登入</button>
            </div>
        </div>
    </form>

{% endblock %}

templates/axf/user/register.html
{% extends 'base_user.html' %}

{% load static %}

{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}

{% block title %}
    {{ block.super }}
    注册
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/register.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/user/js/md5.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <form action="{% url 'axfuser:register' %}" method="post" enctype="multipart/form-data" id="form">

        {% csrf_token %}
        <div class="container">
            <div class="form-group">
                <label for="name">用户名：</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="请输入用户名">
                <span id="nameinfo"></span>
            </div>
            <div class="form-group">
                <label for="password">密码：</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码">
                <span id="pwd"></span>
            </div>
            <div class="form-group">
                <label for="confirmpassword">请确认密码：</label>
                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword"
                       placeholder="请再次输入密码">
                <span id="passwordinfo"></span>
            </div>
            <div class="form-group">
                <label for="email">邮箱：</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="请输入邮箱">
            </div>
            <div class="form-group">
                <label for="icon">头像</label>
                <input type="file" id="icon" name="icon">
            </div>

            <button type="submit" class="btn btn-success btn-block">注册</button>
        </div>
    </form>






{% endblock %}